#!/bin/sh

set -o errexit -o nounset -o pipefail
cd "$(dirname "$0")/.."

compiler='/proj/isaac/tools/sjasmplus/build/sjasmplus'

$compiler \
  --syntax=ab \
  --sym=retroistaba.sym \
  src/main.asm

