#!/bin/sh

set -o errexit -o nounset -o pipefail
cd "$(dirname "$0")/.."

breakpoint_addr () {
  grep breakpoint ./retroistaba.sym | awk '{ print $3 }'
}

breakpoint=$(breakpoint_addr || true)
if [ "$breakpoint" == "" ]; then
  echo "No breakpoints found"
  #fuse ./retroistaba.sna
else
  echo "Breakpoint $breakpoint"
  fuse ./retroistaba.sna --debugger-command="break $(breakpoint_addr)"
fi
