char_e:
        dg xxxxxx--
        dg xx------
        dg xx------
        dg xx------
        dg xxxxx---
        dg xx------
        dg xx------
        dg xx------
       ;dg xxxxxx--

char_i:
        dg xxxxxx--
        dg --xx----
        dg --xx----
        dg --xx----
        dg --xx----
        dg --xx----
        dg --xx----
        dg --xx----
       ;dg xxxxxx--

char_t:
        dg xxxxxx--
        dg --xx----
        dg --xx----
        dg --xx----
        dg --xx----
        dg --xx----
        dg --xx----
        dg --xx----
        dg --xx----

char_b:
        dg xxxxx---
        dg xx--xx--
        dg xx--xx--
        dg xx--xx--
       ;dg xxxxx---
       ;dg xx--xx--
       ;dg xx--xx--
       ;dg xx--xx--
       ;dg xxxxx---

char_r:
        dg xxxxx---
        dg xx--xx--
        dg xx--xx--
        dg xx--xx--
        dg xxxxx---
        dg xx-xx---
        dg xx--xx--
        dg xx--xx--
        dg xx--xx--

char_s:
        dg -xxxx---
        dg xx--xx--
        dg xx------
        dg -xx-----
        dg --xx----
        dg ---xx---
        dg ----xx--
        dg xx--xx--
       ;dg -xxxx---
char_o:
        dg -xxxx---
        dg xx--xx--
        dg xx--xx--
        dg xx--xx--
        dg xx--xx--
        dg xx--xx--
        dg xx--xx--
        dg xx--xx--
        dg -xxxx---



char_a:
        dg --xx----
        dg -xxxx---
        dg xx--xx--
        dg xx--xx--
        dg xx--xx--
        dg xxxxxx--
        dg xx--xx--
        dg xx--xx--
        dg xx--xx--

